### ISSUE TITLE
optional git support?

### ISSUE THREAD

**Issue by jhermann** [RazerM/parver#1]
I have code that generates a dev version with local part like this:

    0.2.0.dev170+0.1.0.gee210cc.20180614T16270

Which is “170 commits after the last release, which is 0.1.0, and the given hash (g…), and a dirty workdir modified last at the given date”. The dirty date is optional.

It is informative and automatic and unique and PEP compatible (which were my requirements).

Interested?

**Comment by RazerM** [comment]
Thanks for the interest, but I'd like to keep anything opinionated out of parver.
